replicaCount: 1

image:
  repository: ajin0809/go-web-app   # Use your DockerHub username & image
  pullPolicy: IfNotPresent
  tag: "17771032965"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: go-web-app.local
      paths:
        - path: /
          pathType: Prefix

